spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: mysql
        dialect: org.hibernate.dialect.MySQL8Dialect